"""
================================================================================================
MODULE: MESH LOADER
================================================================================================

DESCRIPTION:
  Handles loading of external 3D geometry (OBJ, STL, PLY, GLB) using the 'trimesh' library.
  It performs essential preprocessing:
  1. Geometry Cleaning (Fixing normals, duplicates).
  2. Material Conversion (Mapping external materials to our native Lambertian/Metal/Dielectric).
  3. Pivot Adjustment (centering or placing at feet).
  
  Interacts directly with the C++ Engine to upload vertex/face data.

================================================================================================
"""
import trimesh
import numpy as np
import math
import os
import cpp_engine
from dataclasses import dataclass, field

# ==================================================================================
# 1. Structure de données pour les métadonnées
# ==================================================================================

@dataclass
class MeshInfo:
    """Contient les métadonnées géométriques d'un objet chargé."""
    name: str
    
    # Global Bounds (numpy arrays [x, y, z])
    min_coords: np.ndarray
    max_coords: np.ndarray
    size: np.ndarray    # [width, height, depth]
    center: np.ndarray  # Le centre géométrique

    # Infos Matériau par défaut de l'asset
    mat_type: str = "standard"
    color: list = field(default_factory=lambda: [0.8, 0.8, 0.8])
    roughness: float = 0.5
    metallic: float = 0.0
    ior: float = 1.5
    transmission: float = 0.0
    
    # Helpers pratiques (distances depuis le pivot 0,0,0)
    @property
    def height(self): return self.size[1]
    
    @property
    def bottom_y(self): return self.min_coords[1] # Position des pieds par rapport au pivot
    
    def __repr__(self):
        return (f"<MeshInfo '{self.name}': {self.mat_type} | W={self.size[0]:.2f}, H={self.size[1]:.2f}, D={self.size[2]:.2f} | "
                f"Bottom Y={self.bottom_y:.3f}>")

def load_asset(engine, asset_name, file_path, 
               override_mat=None, override_color=None, 
               override_roughness=None, override_metallic=None, 
               override_ior=None, override_transmission=None):
    """
    Loads a mesh into the Engine's Asset Library (memory) WITHOUT adding it to the scene graph.
    Supports PBR overrides.
    """
    if not os.path.exists(file_path):
        print(f"[Error] Mesh file not found: {file_path}")
        return None

    print(f"[Loader] Loading Asset '{asset_name}' from: {file_path}...")
    try:
        scene_or_mesh = trimesh.load(file_path, force=None)
    except Exception as e:
        print(f"[Error] Failed to load mesh: {e}")
        return None

    return process_trimesh_objects(engine, asset_name, scene_or_mesh, 
                                   override_mat, override_color, 
                                   override_roughness, override_metallic, 
                                   override_ior, override_transmission)

def create_cube(engine, size=2.0):
    """Creates a virtual cube asset if it doesn't exist."""
    asset_name = "primitive_cube"
    # Check if already loaded? The engine doesn't expose a 'has_asset' easily here, 
    # but reloading is fine (just updates buffers).
    
    mesh = trimesh.creation.box(extents=[size, size, size])
    # UV mapping for box is simple, trimesh might not generate it perfectly for rendering
    # but for a primitive it's okay. PBR engine needs at least normals (generated by trimesh).
    
    return process_trimesh_objects(engine, asset_name, mesh)

def process_trimesh_objects(engine, asset_name, scene_or_mesh,
                            override_mat=None, override_color=None, 
                            override_roughness=None, override_metallic=None, 
                            override_ior=None, override_transmission=None):
    """
    Internal helper to process a trimesh Scene or Trimesh object and upload to Engine.
    """
    geometries = []
    if isinstance(scene_or_mesh, trimesh.Scene):
        geometries = list(scene_or_mesh.geometry.values())
    else:
        geometries = [scene_or_mesh]

    # --- CALCUL DU PIVOT INTELLIGENT (PIEDS À ZÉRO) ---
    all_verts_raw = []
    for g in geometries: all_verts_raw.append(g.vertices)
    
    center_mass = np.array([0,0,0])
    all_final_verts = [] # Pour MeshInfo

    if all_verts_raw:
        combined = np.vstack(all_verts_raw)
        min_y = combined[:, 1].min()
        mean_x = combined[:, 0].mean()
        mean_z = combined[:, 2].mean()
        center_mass = np.array([mean_x, min_y, mean_z])

    # Default logic PBR (Found in loop)

    for geom in geometries:
        # 1. Extraction des propriétés du fichier (Source of Truth)
        # Valeurs par défaut "safe"
        mat_type = "standard"
        color = [0.8, 0.8, 0.8]
        roughness = 0.5
        metallic = 0.0
        ior = 1.5
        transmission = 0.0
        
        if hasattr(geom, 'visual') and hasattr(geom.visual, 'material'):
            mat = geom.visual.material
            if hasattr(mat, 'name') and mat.name:
                print(f"[Loader]   -> Found Material: '{mat.name}'")
            
            # --- A. Couleur / Albedo ---
            if hasattr(mat, 'diffuse'):
                # trimesh peut renvoyer un color object ou un numpy array
                diff = mat.diffuse
                if isinstance(diff, np.ndarray):
                    if diff.dtype == np.uint8: color = (diff[:3] / 255.0).tolist()
                    else: color = diff[:3].tolist()
                elif isinstance(diff, (list, tuple)) and len(diff) >= 3:
                     # Parfois c'est [r,g,b,a]
                     color = list(diff)[:3]
            # Fallback PBR GLTF
            elif hasattr(mat, 'baseColorFactor'):
                 c = mat.baseColorFactor
                 if len(c) >= 3: color = list(c)[:3]

            # --- B. Roughness ---
            # 1. PBR Direct
            if hasattr(mat, 'roughnessFactor'):
                roughness = float(mat.roughnessFactor)
            # 2. Legacy OBJ (Ns / Shininess)
            elif hasattr(mat, 'shininess'):
                # Mapping empirique: Roughness = sqrt(2 / (Ns + 2))
                # Ns va souvent de 0 à 1000
                ns = float(mat.shininess)
                if ns <= 0.001:
                    roughness = 1.0 # Fully Matte
                else:
                    roughness = math.sqrt(2.0 / (ns + 2.0))
            
            # --- C. Metallic ---
            if hasattr(mat, 'metallicFactor'):
                metallic = float(mat.metallicFactor)
            elif hasattr(mat, 'specular'):
                # Heuristique faible: si specular est très brillant -> metallic ?
                # Pour l'instant, OBJ est souvent diélectrique.
                pass

            # --- D. Transmission / Opacity ---
            # Trimesh 'transparency' est souvent bizarre (d ou Tr).
            # On regarde 'opacity' si dispo (1=opaque, 0=transparent)
            opacity = 1.0
            if hasattr(mat, 'opacity'): # Common in trimesh processed mats
                opacity = float(mat.opacity)
            elif hasattr(mat, 'transparency'):
                # Parfois transparency = 1 - opacity, parfois c'est l'inverse...
                # Trimesh semble normaliser 'transparency' comme alpha si c'est chargé depuis 'd'.
                pass
            
            if opacity < 0.99:
                transmission = 1.0 - opacity
                
            # --- E. IOR ---
            if hasattr(mat, 'ior'): # PBR extension
                ior_val = float(mat.ior)
                if ior_val > 0: ior = ior_val
            # OBJ n'a pas toujours Ni accessible facilement via visual.material standard de trimesh
            # Sauf si PBRMaterial.

        # --- APPLICATION DES OVERRIDES (Priorité Utilisateur) ---
        # Seulement si l'argument est NON-NONE
        if override_mat is not None: mat_type = override_mat
        if override_color is not None: color = override_color
        if override_roughness is not None: roughness = override_roughness
        if override_metallic is not None: metallic = override_metallic
        if override_ior is not None: ior = override_ior
        if override_transmission is not None: transmission = override_transmission

        # 2. Géométrie
        _ = geom.vertex_normals 
        
        verts = geom.vertices.copy()
        verts -= center_mass 
        
        all_final_verts.append(verts.copy())
        
        norms = geom.vertex_normals.copy()
        
        c_verts = np.ascontiguousarray(verts, dtype=np.float32)
        c_norms = np.ascontiguousarray(norms, dtype=np.float32)
        c_faces = np.ascontiguousarray(geom.faces, dtype=np.int32)
        
        # Color safety check
        if isinstance(color, np.ndarray): color = color.tolist()
        if len(color) < 3: color = [0.8, 0.8, 0.8]
        
        vec_color = cpp_engine.Vec3(float(color[0]), float(color[1]), float(color[2]))

        # Enregistrement des infos matériau (pour le MeshInfo final - prend le dernier)
        last_mat_type = mat_type
        last_color = color
        last_rough = float(roughness)
        last_metal = float(metallic)
        last_ior = float(ior)
        last_trans = float(transmission)

        # Envoi à l'engine (Asset)
        engine.load_mesh_asset(asset_name, c_verts, c_faces, c_norms, 
                               mat_type, vec_color, 
                               float(roughness), float(metallic), float(ior), float(transmission))

    # --- C. Construction et Retour de MeshInfo ---
    if all_final_verts:
        total_verts = np.vstack(all_final_verts)
        min_v = total_verts.min(axis=0)
        max_v = total_verts.max(axis=0)
        
        info = MeshInfo(
            name=asset_name,
            min_coords=min_v,
            max_coords=max_v,
            size=max_v - min_v,
            center=(min_v + max_v) / 2.0,
            mat_type=last_mat_type,
            color=last_color,
            roughness=last_rough,
            metallic=last_metal,
            ior=last_ior,
            transmission=last_trans
        )
        print(f"[Loader] Asset Ready: {info}")
        return info

def print_bounds(name, verts):
    """(Optionnel) Affiche les dimensions brutes pour debug rapide."""
    min_v = verts.min(axis=0)
    max_v = verts.max(axis=0)
    width = max_v[0] - min_v[0]
    height = max_v[1] - min_v[1]
    depth = max_v[2] - min_v[2]

    print(f"--- 📏 BOUNDARIES : '{name}' ---")
    print(f"  • Size: {width:.3f} x {height:.3f} x {depth:.3f}")
    print("-----------------------------------")