from vec3 import Vec3, unit_vector, color, dot, random_unit_vector, length_squared, length
from ray import Ray
from hittable import Hittable, HitRecord
from material import ScatterRecord
import numpy as np
import concurrent.futures
import sys
import math

def ray_color(r: Ray, world: Hittable, lights: Hittable, depth: int) -> Vec3:
    if depth <= 0:
        return color(0, 0, 0)
        
    rec = world.hit(r, 0.001, float('inf'))
    if not rec:
        return color(0, 0, 0) # Black background
        
    # Emission
    emitted = rec.material.emit(rec, rec.u, rec.v, rec.p)
    
    scatter_record = rec.material.scatter(r, rec)
    
    if not scatter_record:
        return emitted
        
    if scatter_record.is_specular:
        return convert_if_nan(emitted + scatter_record.attenuation * ray_color(scatter_record.specular_ray, world, lights, depth-1))
        
    # Diffuse Case (NEE)
    # 1. Direct Light Sampling
    direct_light = color(0, 0, 0)
    
    # We need to sample a light source
    # lights is a HittableList or Hittable
    # We assume lights.random(origin) gives a direction towards a light
    
    # Sample light
    light_sample_ray = Ray(rec.p, lights.random(rec.p), r.tm) 
    # Check pdf
    light_pdf_val = lights.pdf_value(rec.p, light_sample_ray.direction)
    
    if light_pdf_val > 0:
        # Check visibility
        hit_light = world.hit(light_sample_ray, 0.001, float('inf'))
        if hit_light:
            # Check if we actually hit the light we aimed at, or just something?
            # For simplicity, if we hit anything, we check if it emitted something.
            # But technically we should check if hit_light.material is emissive.
            # And strict NEE usually requires checking if we hit the explicit light source.
            # Here, we just trust the hit.
            
            # evaluate scattering pdf (BSDF pdf for this light direction)
            scattering_pdf = rec.material.scattering_pdf(r, rec, light_sample_ray)
            if scattering_pdf > 0:
                 li_emit = hit_light.material.emit(hit_light, hit_light.u, hit_light.v, hit_light.p)
                 if length_squared(li_emit) > 0:
                     # Weight = 1 / light_pdf_val
                     # BSDF val? Lambertian scatter returns albedo.
                     # But we need f(p, wi, wo).
                     # For lambertian f = albedo / pi.
                     # Contribution = Li * f * cos_theta / pdf_light
                     
                     # My Lambertian.scattering_pdf returns cos/pi.
                     # So scattering_pdf * pi = cos?
                     # Let's rely on the prompt's formula: "L.emit * material.albedo * geometric_factors"
                     
                     # Standard Monte Carlo: 
                     # Estimate = (Li * f * cos) / pdf
                     # f = albedo / pi
                     # pdf = light_pdf_val (solid angle)
                     
                     # direct_light = li_emit * f * cos / pdf
                     # direct_light = li_emit * (albedo/pi) * cos / pdf
                     
                     # Wait, rec.material.scattering_pdf returns cos/pi. 
                     # So direct_light = li_emit * albedo * scattering_pdf / pdf_light ? 
                     # Only if albedo is pulled out.
                     
                     # Let's interpret "scattering_pdf" as the value of the PDF of the BSDF.
                     # And we know f = albedo * scattering_pdf / cos ? No.
                     
                     # Let's use the robust estimator:
                     # L = emitted
                     # scattering_pdf = val of BSDF pdf
                     # f = albedo * scattering_pdf / (cos_theta / pi)? No that's circular.
                     
                     # Lambertian: f = albedo / pi. 
                     # scattering_pdf = cos / pi.
                     # So f = albedo * scattering_pdf / cos.
                     
                     cos_theta = dot(rec.normal, unit_vector(light_sample_ray.direction))
                     if cos_theta > 0:
                        direct_light = li_emit * scatter_record.attenuation * scattering_pdf / light_pdf_val
    
    # 2. Indirect Light
    # Use the ray generated by scatter (importance sampled by BSDF)
    scattered_ray = scatter_record.specular_ray # Used for diffuse too in my struct
    indirect_light = color(0, 0, 0)
    
    # We need the PDF of this generated ray to weight it?
    # If scatter() performs importance sampling (cosine weighted), then 
    # Weight = 1. (f * cos / pdf = (albedo/pi)*cos / (cos/pi) = albedo).
    # So we just multiply by albedo (attenuation).
    
    indirect_light = scatter_record.attenuation * ray_color(scattered_ray, world, lights, depth-1)
    
    # Combine: If typical NEE, we sum them.
    # Note on double counting:
    # If ray_color(scattered_ray) hits a light, we should IGNORE emission if we already sampled it via NEE.
    # Implementation: In step 2 (Emission), we check if this ray was specular.
    # If it was diffuse bounce (depth < max and !prev_is_specular), we ignore emission.
    # But recursion doesn't pass "prev_is_specular".
    # However, `emitted` is calculated at top.
    # We need to return `emitted` only if "not NEE handled".
    # For this function, `direct_light` handles the light term for THIS bounce.
    # `indirect_light` handles the rest.
    # If `indirect_light` hits a light, it returns `emitted` of that light.
    # We must suppress that emission if it was hit via a diffuse bounce.
    
    # Fix: `ray_color` logic update. 
    # The prompt says: "Si lumière... Si rebond 0 OU spéculaire: Return Emission. Sinon: Return Noir".
    # So I need to know if I am coming from a specular bounce or camera.
    # But I can't easily pass that flag without changing signature or using negative depth hack.
    # Or, I separate Direct and Indirect cleanly.
    
    # Let's follow the prompts logic strictly inside `ray_color`.
    # But wait, `ray_color` is recursive.
    # I can add an argument `allow_emission=True`.
    pass

def ray_color_nee(r: Ray, world: Hittable, lights: Hittable, depth: int, allow_emission: bool = True) -> Vec3:
    if depth <= 0:
        return color(0, 0, 0)

    rec = world.hit(r, 0.001, float('inf'))
    if not rec:
        return color(0, 0, 0)

    emitted = rec.material.emit(rec, rec.u, rec.v, rec.p)
    
    if not allow_emission:
        emitted = color(0, 0, 0) # Suppress emission if this was a diffuse bounce looking for indirect

    srec = rec.material.scatter(r, rec)
    if not srec:
        return emitted

    if srec.is_specular:
        return emitted + srec.attenuation * ray_color_nee(srec.specular_ray, world, lights, depth-1, allow_emission=True)

    # Diffuse / NEE
    # Direct
    direct = color(0, 0, 0)
    
    # Light sample
    light_ray = Ray(rec.p, lights.random(rec.p), r.tm)
    light_pdf = lights.pdf_value(rec.p, light_ray.direction)
    
    if light_pdf > 0:
        hit_light = world.hit(light_ray, 0.001, float('inf'))
        if hit_light:
             li_emit = hit_light.material.emit(hit_light, hit_light.u, hit_light.v, hit_light.p)
             if length_squared(li_emit) > 0:
                 scattering_pdf = rec.material.scattering_pdf(r, rec, light_ray)
                 if scattering_pdf > 0:
                     # Estimator: L * f * cos / pdf
                     # f = albedo / pi
                     # scattering_pdf = cos / pi
                     # -> f = albedo * scattering_pdf / cos
                     cos_theta = dot(rec.normal, unit_vector(light_ray.direction))
                     # term = li_emit * srec.attenuation * scattering_pdf / light_pdf
                     # logic check: 
                     # albedo * (cos/pi) / (cos/pi) ? No. 
                     # Standard: albedo * light_color * (scattering_pdf / light_pdf) ?
                     # Yes, if scattering_pdf is the sampling pdf of the BRDF.
                     # My `scattering_pdf` is `cos/pi`. 
                     # So weight is `(cos/pi) / light_pdf`.
                     # And we multiply by `albedo/pi * cos` ? No.
                     # Term = Le * f * G / pdf_light.
                     # f = albedo/pi.
                     # G = cos_surf * ... (implicit in pdf_light usually?)
                     # No, light_pdf is solid angle pdf.
                     # So Term = Le * f * cos_surf / light_pdf.
                     # Term = Le * (albedo/pi) * cos_surf / light_pdf.
                     # Term = Le * albedo * (cos_surf/pi) / light_pdf.
                     # Term = Le * albedo * scattering_pdf / light_pdf.  <-- This matches
                     direct = li_emit * srec.attenuation * scattering_pdf / light_pdf

    # Indirect
    # Recursive call must suppress emission because we already sampled lights!
    indirect = srec.attenuation * ray_color_nee(srec.specular_ray, world, lights, depth-1, allow_emission=False)
    
    return convert_if_nan(emitted + direct + indirect)

def convert_if_nan(c: Vec3) -> Vec3:
    if np.any(np.isnan(c)):
        return color(0, 0, 0)
    return c

def render_chunk(pixel_indices, image_width, image_height, samples_per_pixel, max_depth, cam, world, lights):
    # pixel_indices is a list of (i, j)
    # Returns list of (i, j, color)
    results = []
    for i, j in pixel_indices:
        pixel_color = color(0, 0, 0)
        for _ in range(samples_per_pixel):
            u = (i + np.random.rand()) / (image_width - 1)
            v = (j + np.random.rand()) / (image_height - 1)
            r = cam.get_ray(u, v)
            pixel_color += ray_color_nee(r, world, lights, max_depth, allow_emission=True)
        results.append((i, j, pixel_color))
    return results

import os

def render_scene(image_width, image_height, samples_per_pixel, max_depth, cam, world, lights):
    
    pixels = np.zeros((image_height, image_width, 3), dtype=np.float32)
    
    # Generate all pixel coords
    # Process in chunks of rows
    # Optimization: Chunk size should be larger to reduce IPC overhead.
    # Let's split into number of CPUs * 4 chunks
    num_workers = os.cpu_count() or 4
    chunk_size = max(1, image_height // (num_workers * 4))
    
    print(f"Rendering {image_width}x{image_height} with {samples_per_pixel} spp...")
    
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = {}
        
        # Create chunks of rows
        for j_start in range(0, image_height, chunk_size):
            j_end = min(j_start + chunk_size, image_height)
            
            chunk_indices = []
            for j in range(j_start, j_end):
                 for i in range(image_width):
                     chunk_indices.append((i, j))
                     
            futures[executor.submit(render_chunk, chunk_indices, image_width, image_height, samples_per_pixel, max_depth, cam, world, lights)] = (j_start, j_end)

        completed = 0
        total_chunks = len(futures)
        
        for future in concurrent.futures.as_completed(futures):
            res = future.result()
            for i, j, col in res:
                pixels[image_height - 1 - j, i] = col / samples_per_pixel
            
            completed += 1
            print(f"Chunks remaining: {total_chunks - completed}   ", end='\r')
                    
    return pixels
